#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FILTERED_DEPS="${SCRIPT_DIR}/../requirements/debian_requirements_filtered.txt"
DOWNLOAD_DIR="${SCRIPT_DIR}/../debian_downloads"

# List of architectures
ARCHITECTURES=("all" "armhf")

# Make sure the download directory exists
rm -rf $DOWNLOAD_DIR
mkdir -p $DOWNLOAD_DIR

# Read each package from the filtered deps file
pushd $DOWNLOAD_DIR
while read package; do
  # Flag to indicate whether download was successful
  download_success=false

  for architecture in "${ARCHITECTURES[@]}"; do
    # Try to download the package
    apt-get download "${package}:${architecture}"

    if [ $? -eq 0 ]; then
      # Download was successful
      download_success=true
      break
    fi
  done

  if [ "$download_success" = false ]; then
    echo "Error: Unable to download any architecture for package $package"
  fi
done < $FILTERED_DEPS
popd

