#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TARGET_DIR="${SCRIPT_DIR}/../lib/python3/dist-packages"

# Update PYTHONPATH
export PYTHONPATH=${TARGET_DIR}:$PYTHONPATH
