#!/usr/bin/env python3
from handrail_segmentation.visualize_detections import *


if __name__ == "__main__":
    rospy.init_node("visualize_detections", anonymous=True)
    my_node = VisualizeImageDetections()
    rospy.spin()