#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DEPS="${SCRIPT_DIR}/../requirements/debian_requirements_root.txt"
COMPLETE_DEPS="${SCRIPT_DIR}/../requirements/debian_requirements_complete.txt"

# Initialize the recursive deps file as empty
rm -f $COMPLETE_DEPS
> $COMPLETE_DEPS

# Read each package from the root deps file
while read package; do
  # Get the recursive dependencies for the package, reverse the order, and append to the recursive deps file
  apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances ${package} | grep "^\w" | tac >> $COMPLETE_DEPS
done < $ROOT_DEPS

# Remove everything after the colon on each line
sed -i 's/:.*//' $COMPLETE_DEPS

# Remove duplicate dependencies
awk '!a[$0]++' $COMPLETE_DEPS > tmp && mv tmp $COMPLETE_DEPS

