#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DOWNLOAD_DIR="${SCRIPT_DIR}/../wheel_downloads"
REQUIREMENTS_FILE="${SCRIPT_DIR}/../requirements/wheel_requirements_root.txt"

# Make sure the download directory exists
rm -rf $DOWNLOAD_DIR
mkdir -p $DOWNLOAD_DIR

# Download all wheels
pip3 wheel -w $DOWNLOAD_DIR -r $REQUIREMENTS_FILE
