#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
COMPLETE_DEPS="${SCRIPT_DIR}/../requirements/debian_requirements_complete.txt"
FILTERED_DEPS="${SCRIPT_DIR}/../requirements/debian_requirements_filtered.txt"

# Initialize the filtered deps file as empty
> $FILTERED_DEPS

# Filter dependencies based on if they're installed
while read package; do
  # Check if the package is installed
  if ! dpkg-query -W -f='${Status}' ${package} 2>/dev/null | grep -q "ok installed"; then
    # If the package is not installed, append it to the filtered deps file
    echo $package >> $FILTERED_DEPS
  fi
done < $COMPLETE_DEPS
